name: Lint

on: [push]

jobs:
  eslint:
    runs-on: windows-latest
    steps:
      - name: Upgrade NPM
        run: npm install -g npm
      - uses: actions/checkout@v1
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2

      