name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Install modules
        run: yarn
      - uses: actions/checkout@v2
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
      