name: Node.js CI

on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Install in the subdirectory
        run: npm run postinstall
      - run: npm test --prefix ./user-service
        env: 
          DB_LOCAL_URI: ${{ secrets.dev.DB_LOCAL_URI }}
          ENV: ${{ secrets.dev.ENV }}
          PORT: ${{ secrets.dev.PORT }}
          COOKIE_SECRET: ${{ secrets.dev.COOKIE_SECRET }}
          SECRET_AUTH_KEY: ${{ secrets.dev.SECRET_AUTH_KEY }}
          SALT_ROUNDS: ${{ secrets.dev.SALT_ROUNDS }}
          CLIENT_DOMAIN: ${{ secrets.dev.CLIENT_DOMAIN }}
          EMAIL_SERVICE: ${{ secrets.dev.EMAIL_SERVICE }}
          EMAIL_USERNAME: ${{ secrets.dev.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.dev.EMAIL_PASSWORD }}